server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      globalcors:

        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /api/auth/**

        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**, /api/employees/**, /api/ai/**, /api/attendance/**, /uploads/**

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**

        - id: project-knowledge-service
          uri: lb://PROJECT-KNOWLEDGE-SERVICE
          predicates:
            - Path=/api/projects/**, /project-docs/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**



eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.loadbalancer: INFO